elasticsearch:
  host: localhost
  port: 9200
  username: "Credential username"
  password: "Credential password"

  index:
    name: board
    shards: 1
    replicas: 0

server:
  port: 8080

spring:
  application:
    name: spring-elasticsearch

otpConfig: production